#!/usr/bin/env bash
# memory-health.sh — Report on structured memory health
#
# Usage: ./scripts/memory-health.sh [MEMORY_DIR]
#   MEMORY_DIR defaults to ~/.openclaw/workspace/memory

set -euo pipefail

MEMORY_DIR="${1:-$HOME/.openclaw/workspace/memory}"
STALE_DAYS="${STALE_DAYS:-90}"
TODAY=$(date +%Y-%m-%d)
THIRTY_DAYS_AGO=$(date -d "-30 days" +%Y-%m-%d 2>/dev/null || date -v-30d +%Y-%m-%d 2>/dev/null || echo "")
STALE_CUTOFF=$(date -d "-${STALE_DAYS} days" +%Y-%m-%d 2>/dev/null || date -v-${STALE_DAYS}d +%Y-%m-%d 2>/dev/null || echo "")

CATEGORIES=("people" "projects" "decisions" "topics" "lessons" "reflections")

echo "# Memory Health Report — $TODAY"
echo ""

# Check if memory dir exists
if [[ ! -d "$MEMORY_DIR" ]]; then
    echo "❌ Memory directory not found: $MEMORY_DIR"
    exit 1
fi

# Count files per category
echo "## File Counts"
echo ""
total=0
for cat in "${CATEGORIES[@]}"; do
    dir="$MEMORY_DIR/$cat"
    if [[ -d "$dir" ]]; then
        count=$(find "$dir" -name "*.md" -type f | wc -l | tr -d ' ')
        echo "- **$cat/**: $count files"
        total=$((total + count))
    else
        echo "- **$cat/**: ⚠️  directory missing"
    fi
done
echo ""
echo "**Total structured files:** $total"
echo ""

# Count daily logs
daily_count=$(find "$MEMORY_DIR" -maxdepth 1 -name "20*.md" -type f | wc -l | tr -d ' ')
echo "**Daily log files:** $daily_count"
echo ""

# MEMORY.md size
memory_md="$MEMORY_DIR/../MEMORY.md"
if [[ -f "$memory_md" ]]; then
    lines=$(wc -l < "$memory_md" | tr -d ' ')
    bytes=$(wc -c < "$memory_md" | tr -d ' ')
    echo "## MEMORY.md"
    echo "- Lines: $lines (target: <150)"
    if [[ "$lines" -gt 150 ]]; then
        echo "- ⚠️  MEMORY.md exceeds 150 lines — consider slimming"
    else
        echo "- ✅ Within target"
    fi
    echo "- Size: $((bytes / 1024))KB"
    echo ""
fi

# Check for stale files (>STALE_DAYS days since last modification)
if [[ -n "$STALE_CUTOFF" ]]; then
    echo "## Staleness Check (>${STALE_DAYS} days)"
    echo ""
    stale_count=0
    for cat in "${CATEGORIES[@]}"; do
        dir="$MEMORY_DIR/$cat"
        [[ -d "$dir" ]] || continue
        while IFS= read -r file; do
            [[ -z "$file" ]] && continue
            mod_date=$(date -r "$file" +%Y-%m-%d 2>/dev/null || stat -c %y "$file" 2>/dev/null | cut -d' ' -f1)
            if [[ "$mod_date" < "$STALE_CUTOFF" ]]; then
                basename=$(basename "$file")
                echo "- ⚠️  **$cat/$basename** — last modified $mod_date"
                stale_count=$((stale_count + 1))
            fi
        done < <(find "$dir" -name "*.md" -type f 2>/dev/null)
    done
    if [[ $stale_count -eq 0 ]]; then
        echo "✅ No stale files"
    else
        echo ""
        echo "**Stale files:** $stale_count"
    fi
    echo ""
fi

# Check for recently updated files (last 30 days)
if [[ -n "$THIRTY_DAYS_AGO" ]]; then
    echo "## Recently Updated (last 30 days)"
    echo ""
    recent_count=0
    for cat in "${CATEGORIES[@]}"; do
        dir="$MEMORY_DIR/$cat"
        [[ -d "$dir" ]] || continue
        while IFS= read -r file; do
            [[ -z "$file" ]] && continue
            mod_date=$(date -r "$file" +%Y-%m-%d 2>/dev/null || stat -c %y "$file" 2>/dev/null | cut -d' ' -f1)
            if [[ "$mod_date" > "$THIRTY_DAYS_AGO" || "$mod_date" == "$THIRTY_DAYS_AGO" ]]; then
                recent_count=$((recent_count + 1))
            fi
        done < <(find "$dir" -name "*.md" -type f 2>/dev/null)
    done
    echo "**Files updated in last 30 days:** $recent_count / $total"
    echo ""
fi

# Check for files missing required frontmatter
echo "## Template Compliance"
echo ""
noncompliant=0
for cat in "${CATEGORIES[@]}"; do
    dir="$MEMORY_DIR/$cat"
    [[ -d "$dir" ]] || continue
    while IFS= read -r file; do
        [[ -z "$file" ]] && continue
        basename=$(basename "$file")
        missing=""
        grep -q '^\*\*Created:\*\*' "$file" 2>/dev/null || missing="${missing}Created, "
        grep -q '^\*\*Updated:\*\*' "$file" 2>/dev/null || missing="${missing}Updated, "
        grep -q '^## Summary' "$file" 2>/dev/null || missing="${missing}Summary, "
        if [[ -n "$missing" ]]; then
            echo "- ⚠️  **$cat/$basename** — missing: ${missing%, }"
            noncompliant=$((noncompliant + 1))
        fi
    done < <(find "$dir" -name "*.md" -type f 2>/dev/null)
done
if [[ $noncompliant -eq 0 ]]; then
    echo "✅ All files have required frontmatter"
fi
echo ""

echo "---"
echo "*Generated by memory-health.sh on $TODAY*"
